apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awaves-web-secrets
  namespace: web
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: awaves-web-secrets
    creationPolicy: Owner
  data:
    - secretKey: mapbox-token
      remoteRef:
        key: awaves/prod/external
        property: mapbox_token
