apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  labels:
    app: react-web
spec:
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
