cloudWatch:
  enabled: true
  region: us-east-1
  logGroupName: /aws/eks/awaves-dev/application
  logStreamPrefix: awaves-
  autoCreateGroup: true

serviceAccount:
  create: true
  name: fluent-bit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::107570140649:role/awaves-fluentbit-role

resources:
  limits:
    memory: 200Mi
  requests:
    cpu: 100m
    memory: 100Mi
