apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: fastapi-api
spec:
  selector:
    app: fastapi-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8001
  type: ClusterIP
