apiVersion: v1
kind: ServiceAccount
metadata:
  name: awaves-api-sa
  namespace: api
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::107570140649:role/awaves-dev-backend-api
    instrumentation.opentelemetry.io/inject-python: "true"