apiVersion: v1
kind: Service
metadata:
  name: mobile-service
  namespace: mobile
  labels:
    app: react-mobile
spec:
  selector:
    app: react-mobile
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
