apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: web
  labels:
    app: react-web
spec:
  selector:
    app: react-web
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
