apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: awaves-api-secrets
  namespace: api
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: awaves-api-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-writer-password
      remoteRef:
        key: awaves/prod/aurora-writer
        property: password
    - secretKey: db-reader-password
      remoteRef:
        key: awaves/prod/aurora-reader
        property: password
    - secretKey: jwt-secret-key
      remoteRef:
        key: awaves/prod/jwt
        property: secret_key
