apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: api
  labels:
    app: fastapi-api
spec:
  selector:
    app: fastapi-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: ClusterIP
