apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: awaves-mobile-secrets
  namespace: mobile
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: awaves-web-secrets           # K8s Secret name referenced by mobile-deployment
    creationPolicy: Owner
  data:
    # Mapbox API token
    - secretKey: mapbox-token
      remoteRef:
        key: awaves/prod/external
        property: mapbox_token
